languageCode = "en-us"
title = "Samrat Jha's Hub"
theme = "github"
Copyright = "Samrat Jha. All rights reserved."
Header = "I spend all my time in Github"

[Author]
  name = "Samrat Jha"

[Permalinks]
  blog = "/:year/:month/:filename/"
  code = "/:filename/"

[params]
  author = "Samrat Jha"
  description = "My personal Github Themed website"
  github = "samratjha96"
  linkedin = "samratjha96"
  email = "samratjha96@gmail.com"
  utterances = "example/example.github.io"
  url = "https://example.com"
  keywords = "samrat jha, website, portfolio"
  darkMode = "true"
