baseurl = "FILL ME IN"
languageCode = "en-us"
title = "FILL ME IN"
theme = "github"
copyright = "Samrat Jha"

[Author]
  name = "Samrat Jha"

[Permalinks]
  blog = "/:year/:month/:filename/"
  code = "/:filename/"
